version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  backend:
    build:
      dockerfile: Dockerfile
    container_name: backend_server
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy


  frontend:
    build:
      context: ../pl/lodz/p/it/frontend/expenseTracker
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "3000:80"
    depends_on:
      - backend